CREATE TABLE IF NOT EXISTS tipos (
	id BIGSERIAL PRIMARY KEY,
	tipo VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS produtos (
	id BIGSERIAL PRIMARY KEY,
	nome VARCHAR(40) NOT NULL,
	estoque INTEGER DEFAULT 0 NOT NULL,
    reserva INTEGER DEFAULT 0,
	valor DECIMAL(10,2) NOT NULL,
	tipo_id BIGINT NOT NULL,
	FOREIGN KEY(tipo_id) REFERENCES tipos(id)
);