ALTER TABLE usuarios ADD COLUMN ativo INTEGER NOT NULL DEFAULT 1;
ALTER TABLE clientes ADD COLUMN ativo INTEGER NOT NULL DEFAULT 1;
ALTER TABLE vendas ADD COLUMN ativo INTEGER NOT NULL DEFAULT 1;
ALTER TABLE fornecedors ADD COLUMN ativo INTEGER NOT NULL DEFAULT 1;
ALTER TABLE produtos ADD COLUMN ativo INTEGER NOT NULL DEFAULT 1;
ALTER TABLE tipos ADD COLUMN ativo INTEGER NOT NULL DEFAULT 1;
